{% set name = "newrelic-telemetry-sdk" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b1303d4167ee059481fd0d11e1d494a5ba5a63d1469c0c8f93804e01d4f5282e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - urllib3 >=1.26,<3

test:
  imports:
    - newrelic_telemetry_sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://newrelic.github.io/newrelic-telemetry-sdk-python
  summary: newrelic-telemetry-sdk-python provides a Python library for sending data into New Relic using the Python urllib3 library. See dimensional metrics, events, logs, and spans/traces in New Relic, without having to use an agent!
  dev_url: https://github.com/newrelic/newrelic-telemetry-sdk-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lrafeei
    - umaannamalai
    - hmstepanek
    - TimPansino
