{% set name = "newrelic-telemetry-sdk" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/newrelic-telemetry-sdk-{{ version }}.tar.gz
  sha256: 461ba12a54f3c44e85e89343d99f66228b4d4703cd2808cefc8fc0b83c97e4e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm
    - pip
  run:
    - python >=3.6
    - urllib3 >=1.7,<2

test:
  imports:
    - newrelic_telemetry_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://newrelic.github.io/newrelic-telemetry-sdk-python
  summary: newrelic-telemetry-sdk-python provides a Python library for sending data into New Relic using the Python urllib3 library. See dimensional metrics, events, logs, and spans/traces in New Relic, without having to use an agent!
  dev_url: https://github.com/newrelic/newrelic-telemetry-sdk-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lrafeei
    - umaannamalai
    - hmstepanek
    - TimPansino
